import React from 'react';
import { motion } from 'motion/react';
import {
  Sparkles,
  AlertTriangle,
  TrendingUp,
  Radar,
  HeartHandshake,
  Gauge,
  CheckCircle,
  BrainCircuit
} from 'lucide-react';
import { AIInsight } from '../types';

interface AIInsightsProps {
  insights: AIInsight[];
  onAcknowledge: (id: string) => void;
  onShowToast?: (message: string, type: 'success' | 'info' | 'warning' | 'error') => void;
}

const cardMotion = (index: number) => ({
  initial: { opacity: 0, y: 16, scale: 0.985 },
  animate: { opacity: 1, y: 0, scale: 1 },
  transition: { duration: 0.42, delay: Math.min(index * 0.05, 0.3), ease: 'easeOut' as const }
});

const typeIcons: Record<AIInsight['type'], typeof Sparkles> = {
  'Risk Alert': AlertTriangle,
  'Resource Forecast': TrendingUp,
  'Anomaly Detection': Radar,
  'Care Recommendation': HeartHandshake
};

const severityStyles: Record<AIInsight['severity'], string> = {
  High: 'bg-rose-50 text-rose-600 border-rose-200',
  Medium: 'bg-amber-50 text-amber-700 border-amber-200',
  Low: 'bg-emerald-50 text-emerald-700 border-emerald-200'
};

const confidenceBarStyles: Record<AIInsight['severity'], string> = {
  High: 'bg-rose-400',
  Medium: 'bg-amber-400',
  Low: 'bg-emerald-400'
};

export default function AIInsights({ insights, onAcknowledge, onShowToast }: AIInsightsProps) {
  const highSeverityCount = insights.filter(i => i.severity === 'High').length;
  const avgConfidence = insights.length
    ? Math.round(insights.reduce((sum, i) => sum + i.confidence, 0) / insights.length)
    : 0;

  const stats = [
    { icon: Sparkles, label: 'Active Insights', value: String(insights.length), sub: 'Awaiting Review', labelColor: 'text-blue-700', iconColor: 'text-[#0066FF]', iconBg: 'bg-pastel-blue' },
    { icon: AlertTriangle, label: 'High Severity', value: String(highSeverityCount), sub: 'Require Action', labelColor: 'text-indigo-700', iconColor: 'text-indigo-600', iconBg: 'bg-pastel-purple' },
    { icon: Gauge, label: 'Avg Confidence', value: `${avgConfidence}%`, sub: 'Across Active Models', labelColor: 'text-purple-700', iconColor: 'text-purple-600', iconBg: 'bg-pastel-pink' },
    { icon: BrainCircuit, label: 'Predictions Today', value: '24', sub: 'Generated by AI Engine', labelColor: 'text-emerald-700', iconColor: 'text-emerald-600', iconBg: 'bg-pastel-green' }
  ];

  const handleAcknowledge = (insight: AIInsight) => {
    onAcknowledge(insight.id);
    onShowToast?.(`Insight "${insight.title}" acknowledged.`, 'success');
  };

  return (
    <main className="flex-1 p-4 md:p-8 space-y-6 lg:pl-72 pb-24 select-none animate-fadeIn">

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="hidden sm:flex w-12 h-12 rounded-full bg-gradient-to-br from-blue-400 to-violet-600 items-center justify-center shadow-card shrink-0">
            <Sparkles className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-lg md:text-xl font-black text-slate-900 tracking-tight">AI Insights</h1>
            <p className="text-[11px] text-slate-500 mt-0.5 font-bold">Predictive alerts, resource forecasts, and care recommendations.</p>
          </div>
        </div>
        <button
          onClick={() => onShowToast?.('AI engine refresh triggered — new insights will appear shortly.', 'info')}
          className="h-10 px-5 bg-[#0066FF] hover:bg-blue-700 text-white rounded-full text-xs font-black flex items-center gap-2 shadow-[0_8px_16px_rgba(0,102,255,0.2)] transition-all cursor-pointer select-none uppercase tracking-wider"
        >
          <Sparkles className="w-3.5 h-3.5" />
          <span>Refresh Insights</span>
        </button>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6">
        {stats.map((stat, idx) => {
          const StatIcon = stat.icon;
          return (
            <motion.div
              key={stat.label}
              {...cardMotion(idx)}
              className="p-5 bg-white border border-slate-100 shadow-card rounded-3xl flex flex-col justify-between hover:shadow-card-hover transition-all duration-300"
            >
              <div className="flex items-center justify-between">
                <span className={`text-[10px] font-black uppercase tracking-widest ${stat.labelColor}`}>{stat.label}</span>
                <div className={`w-9 h-9 rounded-full ${stat.iconBg} flex items-center justify-center`}>
                  <StatIcon className={`w-4.5 h-4.5 ${stat.iconColor}`} />
                </div>
              </div>
              <div className="mt-3">
                <p className="text-2xl font-black text-slate-800 tracking-tight">{stat.value}</p>
                <p className="text-[9px] font-bold text-slate-400 mt-0.5 uppercase tracking-wider">{stat.sub}</p>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Insight feed */}
      <motion.div
        {...cardMotion(stats.length)}
        className="bg-white border border-slate-100 shadow-card rounded-3xl p-6 space-y-4"
      >
        <div>
          <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest">Insight Feed</h3>
          <p className="text-[11px] text-slate-400 mt-0.5">Generated from real-time patient, staffing, and resource data</p>
        </div>

        <div className="space-y-3">
          {insights.length === 0 && (
            <p className="text-xs text-slate-400 font-bold text-center py-8">All insights acknowledged. New predictions will appear here.</p>
          )}
          {insights.map((insight) => {
            const TypeIcon = typeIcons[insight.type];
            return (
              <div
                key={insight.id}
                className="flex flex-col sm:flex-row sm:items-start gap-4 p-4 bg-slate-50 border border-slate-100 rounded-2xl hover:bg-white transition-all"
              >
                <div className="w-10 h-10 rounded-full bg-pastel-blue flex items-center justify-center shrink-0">
                  <TypeIcon className="w-4.5 h-4.5 text-[#0066FF]" />
                </div>

                <div className="flex-1 min-w-0 space-y-1.5">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="text-xs font-black text-slate-800">{insight.title}</p>
                      <p className="text-[10px] text-slate-400 uppercase tracking-wide">{insight.type} • {insight.relatedTo}</p>
                    </div>
                    <span className={`text-[10px] px-2.5 py-1 rounded-full font-black uppercase tracking-wider border shrink-0 ${severityStyles[insight.severity]}`}>
                      {insight.severity}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-500 leading-relaxed">{insight.description}</p>

                  <div className="flex items-center gap-2 pt-1">
                    <div className="flex-1 h-1.5 rounded-full bg-slate-100 overflow-hidden max-w-[180px]">
                      <div className={`h-full rounded-full ${confidenceBarStyles[insight.severity]}`} style={{ width: `${insight.confidence}%` }} />
                    </div>
                    <span className="text-[10px] font-bold text-slate-400">{insight.confidence}% confidence</span>
                    <span className="text-[10px] font-bold text-slate-300">• {insight.timestamp}</span>
                  </div>
                </div>

                <button
                  onClick={() => handleAcknowledge(insight)}
                  className="h-8 px-3 bg-white border border-slate-200 text-slate-600 hover:text-emerald-600 rounded-full text-[10px] font-black uppercase tracking-wider shadow-sm hover:shadow-md transition-all cursor-pointer flex items-center gap-1.5 shrink-0 self-start sm:self-center"
                >
                  <CheckCircle className="w-3.5 h-3.5" />
                  <span>Acknowledge</span>
                </button>
              </div>
            );
          })}
        </div>
      </motion.div>

    </main>
  );
}
